#!/usr/bin/env python3

# binhostess.py is the client-side CLI for binhostess

import time
import argparse
import subprocess
import sys
from pathlib import Path
from dataclasses import dataclass, fields

HERE = Path(__file__).parent

# --- config ---

# /etc/portage/binhostess.conf object
# ngl this was made by LLM
@dataclass
class Conf:
    server_host: str = ""
    server_path: str = ""
    port: int = 8322 # default to 8322 for "BESS" :)

    @staticmethod
    def path() -> Path:
        return Path("/etc/portage/binhostess.conf")

    @classmethod
    def load(cls) -> "Conf":

        conf = cls()
        try:
            warned = False
            for line in cls.path().read_text().splitlines():
                line = line.strip()
                if line.startswith("#"):
                    if warned:
	                #print("[BINHOSTESS::Conf::load] WARNING: comments are ignored, and will be overwritten when saving conf!")
                        warned = True
                    continue
                elif "=" in line:
                    k, v = line.split("=", 1)
                    k, v = k.strip(), v.strip().strip('"')
                    if k in { f.name for f in fields(cls) }:
                        if not v:
                            print(f"[BINHOSTESS::Conf::load] WARNING: {k}'s value is empty!")
                        setattr(conf, k, v)

        except FileNotFoundError:
            print(f"[BINHOSTESS::Conf::load] could not find {Conf.path()} !")
        
        return conf

    def save(self) -> None:
        lines = [ f'{f.name}={getattr(self, f.name)}' for f in fields(self) ]
        try:
            self.path().write_text("\n".join(lines) + "\n")
        except PermissionError:
            print(f"[BINHOSTESS::Conf::save] could not write {self.path()} ! (try running as sudo?)")

    def user(self) -> str:
        return self.server_host.split('@')[0]
    def ip(self) -> str:
        return self.server_host.split('@')[-1]

# --- util functions ---

# runs a shell command on client
def run(args, **kwargs):
    kwargs.setdefault("check", True)
    return subprocess.run(args, **kwargs)

# runs a shell command on server
def remote(cmd, **kwargs):
    conf = Conf.load()
    return run(["ssh", "-t", conf.server_host, f"cd {conf.server_path} && {cmd}"], **kwargs)

# generates the string to be saved at /etc/portage/binrepos.conf/binhostess.conf
def repo_str() -> str:
    conf = Conf.load()
    return f"[binhostess]\npriority={conf.port}\nsync-uri=http://{conf.ip()}:{conf.port}\nlocation=/var/cache/binhost/binhostess\nverify_signature=false\n"

# writes /etc/portage/binrepos.conf/binhostess
def repo():
    run(["sudo", "tee", "/etc/portage/binrepos.conf/binhostess.conf"], input=repo_str(), text=True, stdout=subprocess.DEVNULL)

# generates the string to be saved as docker-compose.yml
def docker_compose_str() -> str:
    return f"""# this file was automatically generated by binhostess

services:
  gentoo:
    image: binhostess:{run(["hostname"], capture_output=True, text=True).stdout.strip()}
    container_name: binhostess
    hostname: binhostess
    volumes:
      - ./etc-portage:/etc/portage
      - ./var-lib-portage:/var/lib/portage
      - ./var-cache-binpkgs:/var/cache/binpkgs
    command: /bin/bash
    stdin_open: true
    tty: true\n
    """

# writes docker-compose.yml
def docker_compose():
    run(["tee", "docker-compose.yml"], input=docker_compose_str(), text=True, stdout=subprocess.DEVNULL)

def binhostess_make_conf_str() -> str:
    conf = Conf.load()
    nproc = run(["ssh", conf.server_host, "nproc"], capture_output=True, text=True).stdout.strip()
    return f"""# this file was automatically generated by binhostess
# to push any changes, run `binhostess sync`

MAKEOPTS=\"-j{nproc} -l{nproc}\"
FEATURES=\"buildpkg -sandbox -usersandbox -network-sandbox -pid-sandbox\"\n
"""

def binhostess_make_conf():
    run(["sudo", "tee", "/etc/portage/binhostess-make.conf"], input=binhostess_make_conf_str(), text=True, stdout=subprocess.DEVNULL)

# TODO: for some reason http_server.terminate() doesnt seem to actually terminate...
# and even a previous server is running, binhost is unable to see it. this temporarily fixes the issue
def clear_port():
    conf = Conf.load()
    remote(f"fuser -k {conf.port}/tcp 2>/dev/null", check=False)

# --- subcommands ---

# prints out the current binhostess config (unformatted)
def get():
    print(Conf.load())

# sets binhostess.conf values
# e.g.: `set server-host user@192.168.0.1`
def set(args):
    conf = Conf.load()

    if args.key not in { f.name for f in fields(Conf) }:
        print(f"[BINHOSTESS::set] unknown key '{args.key}' !")
        return

    setattr(conf, args.key, args.value)

    conf.save()

# syncs server with client. namely:
# /etc/portage/ (excluding binrepos.conf/binhostess.conf),
# /var/lib/portage/world, and 
# /var/lib/portage/world_sets
def sync(args):
    conf = Conf.load()
    host = conf.server_host
    path = conf.server_path
    dest = f"{host}:{path}"

    # push /etc/portage
    print(f"[BINHOSTESS::sync] copying /etc/portage to {dest}/etc-portage ...")
    result = run([
        "rsync", "-avP", "--delete",
        #"--exclude=gnupg/",
        "--exclude=binrepos.conf/binhostess.conf",
        "--exclude=binhostess.conf",
        "/etc/portage/",
        f"{dest}/etc-portage"
    ], check=False)
    if result.returncode not in (0, 23):
        return subprocess.CalledProcessError()

    # push var/lib/portage/world and var/lib/portage/world_sets
    print(f"[BINHOSTESS::sync] copying /var/lib/portage/world and /var/lib/portage/world_sets to {dest}/var-lib-portage ...")
    run([
        "rsync", "-avP",
        "/var/lib/portage/world",
        "/var/lib/portage/world_sets",
        f"{dest}/var-lib-portage/"
    ])

    # cat client-make.conf with binhostess-make.conf
    print(f"[BINHOSTESS::sync] concatinating client-make.conf with server-make.conf ...")
    run([
        "ssh", host,
        f"cd {path}/etc-portage && "
        "mv make.conf client-make.conf && "
        "cat client-make.conf binhostess-make.conf > make.conf"
    ])

    print("[BINHOSTESS::sync] synchronized!")

    if not input("[BINHOSTESS::sync] would you like to 'emerge --sync' ? [y/n] ").lower() in "yes":
        return

    print("[BINHOSTESS::sync] performing 'emerge --sync' on server (in background) ...")
    server_sync = subprocess.Popen(
        ["ssh", conf.server_host, f"cd {conf.server_path} && docker compose exec gentoo emerge --sync"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    print("[BINHOSTESS::sync] performing 'emerge --sync' ...")
    run(["sudo", "emerge", "--sync"], check=False)

    print("[BINHOSTESS::sync] waiting for server to finish ...")
    server_sync.wait()

# creates gentoo docker container
def init(args):
    conf = Conf.load()

    run(["ssh", conf.server_host, "mkdir", "-vp", conf.server_path])

    if args.url:
        hostname = run(["hostname"], capture_output=True, text=True).stdout.strip()
        print(f"[BINHOSTESS::init] creating docker image 'binhostess:{hostname}' ...")
        remote(f"docker import {args.url} binhostess:{hostname}")

    docker_compose()

    print(f"[BINHOSTESS::init] copying docker-compose.yml to {conf.server_host}:{conf.server_path} ...")
    run(["scp", "docker-compose.yml", f"{conf.server_host}:{conf.server_path}/"])
    #print(f"[BINHOSTESS::init] creating mounts to {conf.ip()} in {conf.server_path} as {conf.user()} ...")
    remote("mkdir -vp etc-portage var-lib-portage var-cache-binpkgs")

    answer = input("[BINHOSTESS::init] would you like to remove any existing docker containers? [y/n] ")
    if answer.lower() == "y" or answer.lower() == "yes":
        print("[BINHOSTESS::init] closing container ...")
        remote("docker compose down -v")

    print("[BINHOSTESS::init] starting container \"gentoo\"...")
    remote("docker compose up -d")

    print("[BINHOSTESS::init] writing /etc/portage/binrepos.conf/binhostess.conf ...")
    repo()

    if not Path("/etc/portage/binhostess-make.conf").exists():
        print(f"[BINHOSTESS::init] writing /etc/portage/binhostess-make.conf ...")
        binhostess_make_conf()

    print("[BINHOSTESS::init] initialization complete!")

# opens an binhost http server on server until the user exits (^C)
def host(args):
    conf = Conf.load()
    clear_port()
    print(f"[BINHOSTESS::host] opening http server on port {conf.port}. ^C to close ...")
    remote(f"python3 -m http.server {conf.port} --directory var-cache-binpkgs")

def emerge(args):
    conf = Conf.load()

    print(f"[BINHOSTESS::emerge] performing 'emerge {args.args}' on {conf.server_host} ...")
    remote(f"docker compose exec gentoo emerge {args.args}", check=False)

    clear_port()

    print(f"[BINHOSTESS::emerge] opening binhost http server at {conf.ip()}:{conf.port} ...")
    http_server = subprocess.Popen(
            [ "ssh", conf.server_host,
             f"cd {conf.server_path} && "
             f"python3 -m http.server {conf.port} --directory var-cache-binpkgs", ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

    s = 0
    if s > 0:
        print(f"[BINHOSTESS::emerge] waiting {s} seconds for binhost http server to start ...")
        time.sleep(s)

    print(f"[BINHOSTESS::emerge] performing 'emerge {args.args}' !")
    run(["sudo", "emerge", "--getbinpkg", *args.args.split()], check=False)

    print("[BINHOSTESS::emerge] closing binhost http server ...")
    http_server.terminate()
    http_server.wait()

# executes a shell command inside of the docker container
def exec(args):
    conf = Conf.load()
    host = conf.server_host
    path = conf.server_path
    run(["ssh", "-t", host, f"cd {path} && docker compose exec gentoo {args.cmd}"])

# --- entrypoint ---

def main():
    parser = argparse.ArgumentParser(prog="binhostess", description="binhost emerge syncing service")

    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("get",  help="print the current config")

    set_parser = sub.add_parser("set", help="configure binhostess")
    set_parser.add_argument("key",   help="conf key (e.g.: server_host)")
    set_parser.add_argument("value", help="conf value (e.g.: billie@168.0.0.1)")

    sub.add_parser("sync", help="synchronize server with client")

    init_parser = sub.add_parser("init", help="(re)installs gentoo docker image and/or container on server")
    init_parser.add_argument("url", nargs="?", default=None, help="url of the desired stage3")

    sub.add_parser("host", help="opens the binhost http server")

    emerge_parser = sub.add_parser("emerge", help="emerge on server and copy to client!")
    emerge_parser.add_argument("args", help="the arguments to give to both emerges")

    exec_parser = sub.add_parser("exec", help="[debug] execute a shell command inside docker image")
    exec_parser.add_argument("cmd", help="command to run inside docker container (wrapped in quotes)")

    args = parser.parse_args()
    #print("args:\n", args)

    if args.command == "get":
        get()
    elif args.command == "set":
        set(args)
    elif args.command == "sync":
        sync(args)
    elif args.command == "init":
        init(args)
    elif args.command == "host":
        host(args)
    elif args.command == "emerge":
        emerge(args)
    elif args.command == "exec":
        exec(args)

if __name__ == "__main__":
    main()
