services:
  gentoo:
    image: gentoo/stage3:i686-ssemath-t64-openrc
    container_name: binhostess
    hostname: binhostess
    volumes:
      - ./etc-portage:/etc/portage
      - ./var-lib-portage:/var/lib/portage
      - ./var-cache-binpkgs:/var/cache/binpkgs
    stdin_open: true
    tty: true
